// <auto-generated />
namespace MVCLabTaskLayout.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class InstituteDBv5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InstituteDBv5));
        
        string IMigrationMetadata.Id
        {
            get { return "202504051936195_InstituteDB-v5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
